---
- name: Usage of handlers
  hosts: all
  become: true
  tasks:
  - name: Copy File
    copy:
     content: "hello world"
     dest: /tmp/abc.txt
    notify: restart_apache

  handlers:
  - name: restart_apache
    service: 
      name: httpd
      state: restart
